# Индивидуальное задание 4

## Задание ИЗ 4.1

Прочитайте презентацию «Шифрование и дешифрование сообщений с помощью матриц». 
Зашифруйте слово из 8 букв, используя ту же таблицу, что и в презентации, а кодирующую 
матрицу выберете сами. Обменяйтесь с кем-нибудь зашифрованными словами (и кодирующими 
матрицами) и расшифруйте то, которое получите.

In [233]:
import numpy as np
import pandas as pd

In [202]:
# Зададим кодировочную таблицу в виде словаря
table_code = dict({'А': 25, 'Б': 7, 'В': 14, 'Г': 21, 'Д': 1, 'Е': 12,
                        'Ё': 32, 'Ж': 8, 'З': 10, 'И': 22, 'Й': 24,'К': 15,
                        'Л': 6, 'М': 2, 'Н': 3, 'О': 13, 'П': 35, 'Р': 26,
                        'С': 11, 'Т': 9, 'У': 23, 'Ф': 18, 'Х': 31, 'Ц': 20,
                        'Ч': 29, 'Ш': 16,'Щ': 17, 'Ъ': 27, 'Ы': 30, 'Ь': 19,
                        'Э':33, 'Ю': 4, 'Я': 5, ' ': 28, '!': 34, '.': 36,
                        '\"': 37, ',': 38, '\"': 39, '?': 40, '-': 41, ':': 42})


In [253]:
# Шифрование
matrix_code = np.array([[3, 1], [5, 2]]) # кодирующая матрица
word = 'авиапарк' # слово, требущее расшифровки
word = word.upper()
vector_word = []
vector_code = []
for i in range(len(word)):
    vector_word.append(table_code[word[i]])
if len(vector_word) % 2 != 0:
    vector_word.append(table_code[word[' ']])
i = 0
while i < len(word) - 1:
    vector_code.append(np.array(vector_word[i: i + 2]).dot(matrix_code)[0])
    vector_code.append(np.array(vector_word[i: i + 2]).dot(matrix_code)[1])
    i += 2
vector_code


[145, 53, 191, 72, 230, 85, 153, 56]

In [254]:
# расшифровка
matrix_code = np.array([[1, -1], [2, 3]]) # кодирующая матрица
vector_code = np.array([41, 24, 70, 40, 31, -16, 53, 77]) # шифр
vector_word = []
inverse_matrix = np.linalg.inv(matrix_code)
print("Обратная матрица к матрице шифрования:\n", inverse_matrix)
i = 0
while i < len(vector_code - 1):
    vector_word.append(round(np.array(vector_code[i: i + 2]).dot(inverse_matrix)[0]))
    vector_word.append(round(np.array(vector_code[i: i + 2]).dot(inverse_matrix)[1]))
    i += 2
word = ""
for i in range(len(vector_word)):
    word = word + list(table_code.keys())[list(table_code.values()).index(vector_word[i])]
word


Обратная матрица к матрице шифрования:
 [[ 0.6  0.2]
 [-0.4  0.2]]


'КОРИАНДР'

## Задание ИЗ 4.2

1) Решите задачу:

Если предыдущей покупкой в горнолыжном магазине был сноуборд, то с вероятностью 0,8 
следующей покупкой в этом магазине также будет сноуборд. Если предыдущей покупкой были 
лыжи, то с вероятностью 0,9 следующей покупкой также будут лыжи. Рассчитайте 
распределение вероятностей для третьей покупки, если первой покупкой были лыжи. Для 
иллюстрации переходов к следующей покупке изобразите граф и используйте матрицу 
вероятностей.


In [222]:
# ['Сноуборд', 'Лыжи']
vector_probability = np.array([0, 1])
matrix_transition = np.array([[0.8, 0.2], [0.1, 0.9]])
matrix_iter3 = (vector_probability.dot(matrix_transition)).dot(matrix_transition)
matrix_iter3

array([0.17, 0.83])

2) Придумайте и решите аналогичную задачу.

In [255]:
vector_probability = np.array([1, 0]) # вектор на первой итерации
matrix_transition = np.array([[0.6, 0.4], [0.2, 0.8]]) # матрица переходных вероятностей
iteration = 3 # Количество итерация
matrix = vector_probability
for i in range(iteration - 1):
    matrix = matrix.dot(matrix_transition)
matrix

array([0.44, 0.56])

## Задание ИЗ 4.3
Придумайте и решите две игры по аналогии с примерами, приведенными в учебных 
пособиях и следующих интернет-источниках:

### Решение игры 2 * 2


In [256]:
a11 = 2.5
a12 = 4
a21 = 3
a22 = 2
game = np.array([[a11, a12], [a21, a22]])
x1 = round((game[1][1] - game[1][0])
    /(game[0][0] + game[1][1] - game[0][1] - game[1][0]), 2)
x2 = round(1 - x1, 2)
v = round((game[0][0] * game[1][1] - game[1][0] * game[0][1])
    /(game[0][0] + game[1][1] - game[0][1] - game[1][0]), 2)
print("x1=", x1, " x2=", x2, " v=", v, sep='')


x1=0.4 x2=0.6 v=2.8


### Игра с седловой точкой

In [190]:
# Задаем игровую матрицу
matrix = np.array([[2, -3, 4, -5, 6, -7], 
                    [-3, 4, -5, 6, -7, 8],
                    [4, -5, 6, -7, 8, -9],
                    [-5, 6, -7, 8, -9, 10],
                    [-5, 6, -7, 8, -9, 10]])
alpha = min(matrix[0])
for i in range(1, matrix.shape[0]):
    if min(matrix[i]) > alpha:
        alpha = min(matrix[i])
beta = max(matrix[:,0])
for i in range(1, matrix.shape[1]):
    if max(matrix[:,i]) < beta:
        beta = max(matrix[:,i])
print("Нижняя цена игры: ", alpha)
print("Верхняя цена игры: ", beta)

Нижняя цена игры:  6
Верхняя цена игры:  6


### Игра с природой

In [232]:
# Задайте игровую матрицу, стратегии и параметр пессимистичности для расчета критерия Гурвица
matrix = np.array([[1, 2, 3, 5, 1], [4, 6, 1, 3, 6], [7, 2, 4, 8, 2], [3, 1, 6, 1, 7]])
vector_strategy = np.array([1, 2, 3])
alpha = 0.5
# Критерий Вальда
utility = min(matrix[0])
strategy_pes = 1
for i in range(1, matrix.shape[0]):
    if min(matrix[i]) > utility:
        strategy_pes = i + 1
        utility = min(matrix[i])
print("Критерий Вальда. Полезность =", utility, ", стратегия - ", vector_strategy[strategy_pes - 1])
# Критерий оптимиста
utility = max(matrix[0])
strategy_opt = 1
for i in range(1, matrix.shape[0]):
    if max(matrix[i]) > utility:
        strategy_opt = i + 1
        utility = max(matrix[i])
print("Критерий оптимиста. Полезность =", utility, ", стратегия - ", vector_strategy[strategy_opt - 1])
# Критерий Гурвица
print("Критерий Гурвица. Стратегия - ", vector_strategy[strategy_opt - 1]
    + alpha * (vector_strategy[strategy_pes - 1] - vector_strategy[strategy_opt - 1]))

Критерий Вальда. Полезность = 2 , стратегия -  3
Критерий оптимиста. Полезность = 8 , стратегия -  3
Критерий Гурвица. Стратегия -  3.0


## Задание ИЗ 4.4
Решите в Excel методом Крамера и методом обратной матрицы систему уравнений из 
своего варианта.

In [257]:
var = pd.read_excel('ИЗ_4_Варианты.xlsx')

In [258]:
# Введите номер варианта
variant = 3
a11 = var.iloc[variant - 1]['a11']
a12 = var.iloc[variant - 1]['a12']
a13 = var.iloc[variant - 1]['a13']
a14 = var.iloc[variant - 1]['a14']
b1 = var.iloc[variant - 1]['b1']
a21 = var.iloc[variant - 1]['a21']
a22 = var.iloc[variant - 1]['a22']
a23 = var.iloc[variant - 1]['a23']
a24 = var.iloc[variant - 1]['a24']
b2 = var.iloc[variant - 1]['b2']
a31 = var.iloc[variant - 1]['a31']
a32 = var.iloc[variant - 1]['a32']
a33 = var.iloc[variant - 1]['a33']
a34 = var.iloc[variant - 1]['a34']
b3 = var.iloc[variant - 1]['b3']
a41 = var.iloc[variant - 1]['a41']
a42 = var.iloc[variant - 1]['a42']
a43 = var.iloc[variant - 1]['a43']
a44 = var.iloc[variant - 1]['a44']
b4 = var.iloc[variant - 1]['b4']

### Метод Крамера

In [259]:
A = np.array([[a11, a12, a13, a14], [a21, a22, a23, a24],
    [a31, a32, a33, a34], [a41, a42, a43, a44]])
det = np.linalg.det(A)
det1 = np.linalg.det(np.array([[b1, a12, a13, a14], [b2, a22, a23, a24],
    [b3, a32, a33, a34], [b4, a42, a43, a44]]))
det2 = np.linalg.det([[a11, b1, a13, a14], [a21, b2, a23, a24],
    [a31, b3, a33, a34], [a41, b4, a43, a44]])
det3 = np.linalg.det([[a11, a12, b1, a14], [a21, a22, b2, a24],
    [a31, a32, b3, a34], [a41, a42, b4, a44]])
det4 = np.linalg.det([[a11, a12, a13, b1], [a21, a22, a23, b2],
    [a31, a32, a33, b3], [a41, a42, a43, b4]])
print("Основной определитель: ", round(det, 2))
print("Определитель дельта 1: ", round(det1, 2))
print("Определитель дельта 2: ", round(det2, 2))
print("Определитель дельта 3: ", round(det3, 2))
print("Определитель дельта 4: ", round(det4, 2))
print("x1 =", round(det1 / det, 2))
print("x2 =", round(det2 / det, 2))
print("x3 =", round(det3 / det, 2))
print("x4 =", round(det4 / det, 2))

Основной определитель:  8706.0
Определитель дельта 1:  -0.0
Определитель дельта 2:  -78354.0
Определитель дельта 3:  8706.0
Определитель дельта 4:  34824.0
x1 = -0.0
x2 = -9.0
x3 = 1.0
x4 = 4.0


### Метод обратной матрицы

In [252]:
B = np.array([b1, b2, b3, b4])
inverse_matrix = np.linalg.inv(A)
print(inverse_matrix)
inverse_matrix.dot(B)

[[ 0.07901235 -0.00246914  0.30617284 -0.2691358 ]
 [-0.02469136 -0.0617284  -0.34567901  0.27160494]
 [ 0.01135802 -0.03160494 -0.28098765  0.35506173]
 [ 0.08098765  0.12246914  0.21382716 -0.2508642 ]]


array([ 1., -2., -6.,  2.])