# Индивидуальное задание 4

## Задание ИЗ 4.1

Прочитайте презентацию «Шифрование и дешифрование сообщений с помощью матриц». 
Зашифруйте слово из 8 букв, используя ту же таблицу, что и в презентации, а кодирующую 
матрицу выберете сами. Обменяйтесь с кем-нибудь зашифрованными словами (и кодирующими 
матрицами) и расшифруйте то, которое получите.

In [2]:
import numpy as np
import pandas as pd

In [8]:
# Зададим кодировочную таблицу в виде словаря
table_code = dict({'А': 25, 'Б': 7, 'В': 14, 'Г': 21, 'Д': 1, 'Е': 12,
                        'Ё': 32, 'Ж': 8, 'З': 10, 'И': 22, 'Й': 24,'К': 15,
                        'Л': 6, 'М': 2, 'Н': 3, 'О': 13, 'П': 35, 'Р': 26,
                        'С': 11, 'Т': 9, 'У': 23, 'Ф': 18, 'Х': 31, 'Ц': 20,
                        'Ч': 29, 'Ш': 16,'Щ': 17, 'Ъ': 27, 'Ы': 30, 'Ь': 19,
                        'Э':33, 'Ю': 4, 'Я': 5, ' ': 28, '!': 34, '.': 36,
                        '\"': 37, ',': 38, '\"': 39, '?': 40, '-': 41, ':': 42})


In [157]:
# Шифрование
matrix_code = np.array([[1, 3], [0, -1]]) # кодирующая матрица
word = 'аквапарк' # слово, требущее расшифровки
word = word.upper()
vector_word = []
vector_code = []
for i in range(len(word)):
    vector_word.append(table_code[word[i]])
if len(vector_word) % 2 != 0:
    vector_word.append(table_code[' '])
i = 0
while i < len(word) - 1:
    vector_code.append(np.array(vector_word[i: i + 2]).dot(matrix_code)[0])
    vector_code.append(np.array(vector_word[i: i + 2]).dot(matrix_code)[1])
    i += 2
vector_code


[25, 60, 14, 17, 35, 80, 26, 63]

In [158]:
# расшифровка
matrix_code = np.array([[2, 1], [5, 3]]) # кодирующая матрица
vector_code = np.array([195, 110, 97, 53, 94, 52, 65, 34]) # шифр
vector_word = []
inverse_matrix = np.linalg.inv(matrix_code)
print("Обратная матрица к матрице шифрования:\n", inverse_matrix)
i = 0
while i < len(vector_code - 1):
    vector_word.append(round(np.array(vector_code[i: i + 2]).dot(inverse_matrix)[0]))
    vector_word.append(round(np.array(vector_code[i: i + 2]).dot(inverse_matrix)[1]))
    i += 2
word = ""
print(vector_word)
for i in range(len(vector_word)):
    word = word + list(table_code.keys())[list(table_code.values()).index(vector_word[i])]
word


Обратная матрица к матрице шифрования:
 [[ 3. -1.]
 [-5.  2.]]
[35, 25, 26, 9, 22, 10, 25, 3]


'ПАРТИЗАН'

## Задание ИЗ 4.2

1) Решите задачу:

Если предыдущей покупкой в горнолыжном магазине был сноуборд, то с вероятностью 0,8 
следующей покупкой в этом магазине также будет сноуборд. Если предыдущей покупкой были 
лыжи, то с вероятностью 0,9 следующей покупкой также будут лыжи. Рассчитайте 
распределение вероятностей для третьей покупки, если первой покупкой были лыжи. Для 
иллюстрации переходов к следующей покупке изобразите граф и используйте матрицу 
вероятностей.


In [108]:
# ['Сноуборд', 'Лыжи']
vector_probability = np.array([1, 0])
matrix_transition = np.array([[0.1, 0.9], [0.4, 0.6]])
matrix_iter3 = (vector_probability.dot(matrix_transition)).dot(matrix_transition)
matrix_iter3

array([0.37, 0.63])

2) Придумайте и решите аналогичную задачу.

In [159]:
vector_probability = np.array([0, 1]) # вектор на первой итерации
matrix_transition = np.array([[0.7, 0.3], [0.4, 0.6]]) # матрица переходных вероятностей
iteration = 3 # Количество итерация
matrix = vector_probability
for i in range(iteration - 1):
    matrix = matrix.dot(matrix_transition)
matrix

array([0.52, 0.48])

## Задание ИЗ 4.3
Придумайте и решите две игры по аналогии с примерами, приведенными в учебных 
пособиях и следующих интернет-источниках:


In [16]:
def saddle_point(matrix):
    alpha = min(matrix[0])
    for i in range(1, matrix.shape[0]):
        if min(matrix[i]) > alpha:
            alpha = min(matrix[i])
    beta = max(matrix[:,0])
    for i in range(1, matrix.shape[1]):
        if max(matrix[:,i]) < beta:
            beta = max(matrix[:,i])
    return (alpha, beta)

def mixed_strategies(game):
    alpha, beta = saddle_point(matrix)
    if alpha == beta:
        print("Игра имеет решение в чистых стратегиях")
        print("Седловая точка =", alpha)
        return
    x1 = round((game[1][1] - game[1][0])
        /(game[0][0] + game[1][1] - game[0][1] - game[1][0]), 2)
    x2 = round(1 - x1, 2)
    v = round((game[0][0] * game[1][1] - game[1][0] * game[0][1])
        /(game[0][0] + game[1][1] - game[0][1] - game[1][0]), 2)
    print("x1=", x1, " x2=", x2, " v=", v, sep='')
    

### Игра с седловой точкой

In [122]:
# Задаем игровую матрицу
matrix = np.array([[-5, 4, -1], 
                    [3, 6, -2],
                    [7, 5, 8]])
alpha, beta = saddle_point(matrix)
print("Нижняя цена игры: ", alpha)
print("Верхняя цена игры: ", beta)

Нижняя цена игры:  5
Верхняя цена игры:  6


### Решение игры 2 * 2 в смешанных стратегиях

In [132]:
a11 = 1
a12 = 4
a21 = 3
a22 = 2
matrix = np.array([[a11, a12], [a21, a22]])
mixed_strategies(matrix)

x1=0.25 x2=0.75 v=2.5


### Игра с природой

In [133]:
# Задайте игровую матрицу, стратегии и параметр пессимистичности для расчета критерия Гурвица
matrix = np.array([[1, 7, 2, 6],
                    [5, 4, 1, 3],
                    [2, 3, 5, 7]])
vector_strategy = np.array([1, 2, 3])
alpha = 0.8
# Критерий Вальда
utility = min(matrix[0])
strategy_pes = 1
for i in range(1, matrix.shape[0]):
    if min(matrix[i]) > utility:
        strategy_pes = i + 1
        utility = min(matrix[i])
print("Критерий Вальда. Полезность =", utility, ", стратегия - ", vector_strategy[strategy_pes - 1])
# Критерий оптимиста
utility = max(matrix[0])
strategy_opt = 1
for i in range(1, matrix.shape[0]):
    if max(matrix[i]) > utility:
        strategy_opt = i + 1
        utility = max(matrix[i])
print("Критерий оптимиста. Полезность =", utility, ", стратегия - ", vector_strategy[strategy_opt - 1])
# Критерий Гурвица
print("Критерий Гурвица. Стратегия - ", vector_strategy[strategy_opt - 1]
    + alpha * (vector_strategy[strategy_pes - 1] - vector_strategy[strategy_opt - 1]))

Критерий Вальда. Полезность = 2 , стратегия -  3
Критерий оптимиста. Полезность = 7 , стратегия -  1
Критерий Гурвица. Стратегия -  2.6


## Задание ИЗ 4.4
Решите в Excel методом Крамера и методом обратной матрицы систему уравнений из 
своего варианта.

In [151]:
var = pd.read_excel('ИЗ_4_Варианты.xlsx')

In [160]:
# Введите номер варианта
variant = 13
a11 = var.iloc[variant - 1]['a11']
a12 = var.iloc[variant - 1]['a12']
a13 = var.iloc[variant - 1]['a13']
a14 = var.iloc[variant - 1]['a14']
b1 = var.iloc[variant - 1]['b1']
a21 = var.iloc[variant - 1]['a21']
a22 = var.iloc[variant - 1]['a22']
a23 = var.iloc[variant - 1]['a23']
a24 = var.iloc[variant - 1]['a24']
b2 = var.iloc[variant - 1]['b2']
a31 = var.iloc[variant - 1]['a31']
a32 = var.iloc[variant - 1]['a32']
a33 = var.iloc[variant - 1]['a33']
a34 = var.iloc[variant - 1]['a34']
b3 = var.iloc[variant - 1]['b3']
a41 = var.iloc[variant - 1]['a41']
a42 = var.iloc[variant - 1]['a42']
a43 = var.iloc[variant - 1]['a43']
a44 = var.iloc[variant - 1]['a44']
b4 = var.iloc[variant - 1]['b4']

### Метод Крамера

In [161]:
A = np.array([[a11, a12, a13, a14], [a21, a22, a23, a24],
    [a31, a32, a33, a34], [a41, a42, a43, a44]])
det = np.linalg.det(A)
det1 = np.linalg.det(np.array([[b1, a12, a13, a14], [b2, a22, a23, a24],
    [b3, a32, a33, a34], [b4, a42, a43, a44]]))
det2 = np.linalg.det([[a11, b1, a13, a14], [a21, b2, a23, a24],
    [a31, b3, a33, a34], [a41, b4, a43, a44]])
det3 = np.linalg.det([[a11, a12, b1, a14], [a21, a22, b2, a24],
    [a31, a32, b3, a34], [a41, a42, b4, a44]])
det4 = np.linalg.det([[a11, a12, a13, b1], [a21, a22, a23, b2],
    [a31, a32, a33, b3], [a41, a42, a43, b4]])
print("Основной определитель: ", round(det, 2))
print("Определитель дельта 1: ", round(det1, 2))
print("Определитель дельта 2: ", round(det2, 2))
print("Определитель дельта 3: ", round(det3, 2))
print("Определитель дельта 4: ", round(det4, 2))
print("x1 =", round(det1 / det, 2))
print("x2 =", round(det2 / det, 2))
print("x3 =", round(det3 / det, 2))
print("x4 =", round(det4 / det, 2))

Основной определитель:  -2000.0
Определитель дельта 1:  18000.0
Определитель дельта 2:  -8000.0
Определитель дельта 3:  20000.0
Определитель дельта 4:  -10000.0
x1 = -9.0
x2 = 4.0
x3 = -10.0
x4 = 5.0


### Метод обратной матрицы

In [145]:
B = np.array([b1, b2, b3, b4])
inverse_matrix = np.linalg.inv(A)
print(inverse_matrix)
inverse_matrix.dot(B)

[[-0.57560976 -0.62926829 -0.0195122   0.77560976]
 [-0.46341463 -0.24390244  0.17073171  0.46341463]
 [-0.20487805  0.16585366  0.04390244  0.00487805]
 [-0.21463415  0.69756098  0.33170732 -0.18536585]]


array([-5., -6.,  8.,  6.])